version: "3.8"

services:
  db:
    image: postgres:17
    container_name: onboarding-db
    environment:
      POSTGRES_DB: onboarding
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@R1o2h3i4t5@"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: onboarding-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/onboarding
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "@R1o2h3i4t5@"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    command: ["java", "-jar", "/app/onboarding-0.0.1-SNAPSHOT.jar"]
    volumes:
      - ./target/onboarding-0.0.1-SNAPSHOT.jar:/app/onboarding-0.0.1-SNAPSHOT.jar

volumes:
  pgdata:
